apiVersion: v1
kind: Service
metadata:
  name: gha-java-app
  labels:
    app: gha-java-app
spec:
  type: LoadBalancer
  selector:
    app: gha-java-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP