name: CI Java APP using sonar, trivy and docker
on:
  push:
    branches: [ main ]
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
env:
  AWS_REGION: us-east-1
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Perform Static Code Analysis with SonarQube
      run: | 
        mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=gha-java-app
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Fail if Quality Gate Fails
      uses: sonarsource/sonarqube-quality-gate-action@v1
      timeout-minutes: 5
      with:
        scanMetadataReportFile: target/sonar/report-task.txt
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::927749346049:role/github-actions-dev-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create Short SHA
      run: echo "SHORT_SHA=$(git rev-phase --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image to ECR
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/927749346049.dkr.ecr.us-east-1.amazonaws.com/gha-java-app:${{ env.SHORT_SHA }}
    
