name: CI Java APP using sonar, trivy and docker
on:
  push:
    branches: [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Perform Static Code Analysis with SonarQube
      run: | 
        mvn -B clean verify\
         org.sonarsource.scanner.maven:sonar-maven-plugin:sonar\
         -Dsonar.projectKey=gha-java-app\
         -Dsonar.gateway.wait=true\
         -Dsonar.gateway.timeout=300
      env: 
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
